on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.6.1
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Formatting
        run: yarn format:check
      - name: Linter
        run: yarn lint
      - name: Run Type-Checker
        run: yarn typecheck
      # - name: Run Tests
      #   run: yarn test
      - name: Run Build
        run: yarn build